
name: Deploy cliente to VPS
 
on:
  push:
    branches: [ "main" ]
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
 
      - name: Copy project to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "clientes-1.jar,dockerfile"
          target: "~/SpringTest/docker-cliente"
 
      - name: Deploy on VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/SpringTest/docker-cliente
            docker build -t cliente-app .
            docker network create spring-net || true
            docker stop cliente-app || true
            docker rm cliente-app || true
            docker run -d --name cliente-app \
              --network spring-net \
              --memory="1024m" \
              --cpus="1" \
              -e SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/manager \
              -e SPRING_DATASOURCE_USERNAME=root \
              -e SPRING_DATASOURCE_PASSWORD=cruz123 \
              -p 8090:8090 cliente-app
